### ISSUE TITLE
dcos package fails with new available pip version

### ISSUE THREAD

**Issue by sttts** [mesosphere/dcos-cli#222]
My dcos setup worked fine. Today "dcos package install kubernetes" failed without any sensible error message:
```
Error installing 'kubernetes' package
```
With log-level set to `debug` I get this:
```
...
Creating directory: '/Users/sts/.dcos/subcommands/kubernetes'
Calling: ['/Users/sts/Quellen/mesos/dcos-cli/cli/env/bin/virtualenv', '/Users/sts/.dcos/subcommands/kubernetes/env']
Install script's stdout: Using real prefix '/System/Library/Frameworks/Python.framework/Versions/2.7'
New python executable in /Users/sts/.dcos/subcommands/kubernetes/env/bin/python
Installing setuptools, pip...done.

Install script's stderr: 
Calling: ['/Users/sts/.dcos/subcommands/kubernetes/env/bin/pip', 'install', '--requirement', '/var/folders/gg/zn9yfdld21j7xg5jnj5zz5d80000gn/T/tmp1W0OCQ']
Install script's stdout: 
Install script's stderr: You are using pip version 6.1.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
    status = self.run(options, args)
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    finder=finder, options=options, session=session):
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_file.py", line 135, in parse_requirements
    isolated=options.isolated_mode if options else False,
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_install.py", line 220, in from_line
    isolated=isolated)
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_install.py", line 79, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/Users/sts/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'git@github.com:mesosphere/dcos-kubernetes-cli.git#egg=dcos-kubernetes', 'at', '@github.com:mesosphere/dcos-kubernetes-cli.git#egg=dcos-kubernetes')
```

**Comment by jsancio** [comment]
Okay, but I don't think we should specify Python packages (egg or wheels) using the SCM specification: `git@github.com:mesosphere/dcos-kubernetes-cli.git#egg=dcos-kubernetes`. We should change the universe entry to instead install from PyPI.

**Comment by sttts** [comment]
This is for development only right now. We don't have a release version of dcos-k8s yet.
