### ISSUE TITLE
Error installing 'spark' package

### ISSUE THREAD

**Issue by anubhavsinha** [mesosphere/dcos-cli#398]
[ec2-user@ip-172-31-50-60 dcos]$ dcos --log-level=ERROR package install spark
Note that the Apache Spark DCOS Service is beta and there may be bugs, incomplete features, incorrect documentation or other discrepancies.
We recommend a minimum of two nodes with at least 2 CPU and 2GB of RAM available for the Spark Service and running a Spark job.
Note: The Spark CLI may take up to 5min to download depending on your connection.
Continue installing? [yes/no] yes
Installing Marathon app for package [spark] version [1.5.0-multi-roles-v2]
Installing CLI subcommand for package [spark] version [1.5.0-multi-roles-v2]
2016-01-01 04:51:13,440 /home/ec2-user/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py:_execute_install:411 - Install script's stdout: Collecting dcos-spark==0.4.0-spark-1.5.0-multi-roles-v2-bin-2.4.0 from https://s3.amazonaws.com/downloads.mesosphere.io/dcos/spark/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl (from -r /tmp/tmpK6g6X2 (line 1))
  Downloading https://s3.amazonaws.com/downloads.mesosphere.io/dcos/spark/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl (228.9MB)

2016-01-01 04:51:13,440 /home/ec2-user/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py:_execute_install:412 - Install script's stderr: Exception:
Traceback (most recent call last):
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/utils/ui.py", line 133, in iter
    for x in it:
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 49, in dumps
    "body": _b64_encode_bytes(body),
  File "/home/ec2-user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
  File "/usr/lib64/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
MemoryError

Error installing 'spark' package.

**Comment by anubhavsinha** [comment]
[ec2-user@ip-172-31-50-60 dcos]$ dcos --log-level=ERROR package install --package-version=1.4.0-SNAPSHOT spark
Note that the Apache Spark DCOS Service is beta and there may be bugs, incomplete features, incorrect documentation or other discrepancies.
We recommend a minimum of two nodes with at least 2 CPU and 2GB of RAM available for the Spark Service and running a Spark job.
Note: The Spark CLI may take up to 5min to download depending on your connection.
Continue installing? [yes/no] yes
Installing Marathon app for package [spark] version [1.4.0-SNAPSHOT]
Installing CLI subcommand for package [spark] version [1.4.0-SNAPSHOT]
New command available: dcos spark
The Apache Spark DCOS Service has been successfully installed!

	Documentation: https://spark.apache.org/docs/latest/running-on-mesos.html
	Issues: https://issues.apache.org/jira/browse/SPARK

**Comment by anubhavsinha** [comment]
This works for latest Spark 1.6 now.
