### ISSUE TITLE
dcos kubernetes failed on OSX

### ISSUE THREAD

**Issue by miry** [mesosphere/dcos-cli#410]
I have next issue:

```
$ bin/dcos-kubectl kubectl --info
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: <HOME>/.dcos/subcommands/kubernetes/env/bin/python2.7
  Reason: image not found
[1]    40818 trace trap <HOME>/.dcos/subcommands/kubernetes/env/bin/dcos-kubectl kubectl --info
```

```
$ ./bin/dcos     
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/miry/.dcos/subcommands/kubernetes/env/bin/python2.7
  Reason: image not found
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/miry/.dcos/subcommands/kubernetes/env/bin/python2.7
  Reason: image not found
Traceback (most recent call last):
  File "/Users/miry/projects/oos/dcos/bin/dcos-help", line 11, in <module>
    sys.exit(main())
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcoscli/help/main.py", line 17, in main
    return _main()
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcoscli/main.py", line 112, in wrapper
    result = func(*args, **kwargs)
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcoscli/help/main.py", line 31, in _main
    return cmds.execute(_cmds(), args)
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcoscli/help/main.py", line 89, in _help
    .make_command_summary_string(sorted(results))
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/concurrent/futures/_base.py", line 581, in result_iterator
    yield future.result()
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcos/subcommand.py", line 132, in documentation
    return (path_noun, info(executable_path, path_noun))
  File "/Users/miry/projects/oos/dcos/lib/python2.7/site-packages/dcos/subcommand.py", line 147, in info
    [executable_path, path_noun, '--info'])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/miry/.dcos/subcommands/kubernetes/env/bin/dcos-kubectl', 'kubectl', '--info']' returned non-zero exit status -5
```

```
 $ ./bin/dcos --version
dcos version 0.3.0
$ uname -a
Darwin host.local 15.4.0 Darwin Kernel Version 15.4.0: Sun Jan  3 21:35:22 PST 2016; root:xnu-3248.40.155~11/RELEASE_X86_64 x86_64

```

**Comment by jdef** [comment]
@sttts does error hold any meaning for you?

**Comment by sttts** [comment]
@miry isn't that an unreleased OSX version? Is your python compatible with that? Is python coming from homebrew? does homebrew support the OSX version? Googling for the error gives a number of hits which look promising to fix broken virtualenvs: https://www.google.de/search?client=safari&rls=en&q=dyld:+Library+not+loaded:+@executable_path/../.Python&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=HgGgVrW3II-r8wfTp7EI

**Comment by miry** [comment]
@sttts 
 > isn't that an unreleased OSX version?

yes. I have 10.11.4 Beta (15E27e)

>  Is your python compatible with that? Is python coming from homebrew? does homebrew support the OSX version? 

python was installed via hombrew.  brew doctor says `Your system is ready to brew.` 

> Googling for the error gives a number of hits which look promising to fix broken virtualenvs

I upgraded virtualenv via pip like was described in the docs. Will look to this solutions from google.

@sttts Is it possible to remove kubernetes plugin ?

**Comment by miry** [comment]
removed cached folder `~/.dcos` and reinstalled cli.
