### ISSUE TITLE
Add a `marathon app save` and `marathon app load`

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/dcos-cli#458]
save would `save` a marathon.json to disk, which could then be used with `load` to put it back into the cluster (HTTP PUT rather than POST since Marathon has different behavior on PUT). Currently I can sort of hack this together with bash around dcos marathon app show and dcos marathon app add, but it isn't very clean and doesn't always work.

Ideally there would be a `marathon group` version of these around, and if I passed it the group `/` it would save all apps.

**Comment by jsancio** [comment]
@aquamatthias Does marathon provide his functionality? Or are we going to have to filter the properties ourselves?

@cmaloney Can you let me know what filters you are performing now?

**Comment by cmaloney** [comment]
Currently I have a GET of `/v2/apps` which someone gave me which I can't use any of the marathon CLI commands in order to re-add. When I tried to add it using the CLI I got a number of different erros when I did it different ways
```
➜  tmp  dcos marathon app add marathon.json 
Traceback (most recent call last):
  File "/home/cody/tmp/dcos/bin/dcos-marathon", line 11, in <module>
    sys.exit(main())
  File "/home/cody/tmp/dcos/lib/python3.5/site-packages/dcoscli/marathon/main.py", line 20, in main
    return _main()
  File "/home/cody/tmp/dcos/lib/python3.5/site-packages/dcoscli/main.py", line 112, in wrapper
    result = func(*args, **kwargs)
  File "/home/cody/tmp/dcos/lib/python3.5/site-packages/dcoscli/marathon/main.py", line 34, in _main
    return cmds.execute(_cmds(), args)
  File "/home/cody/tmp/dcos/lib/python3.5/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/home/cody/tmp/dcos/lib/python3.5/site-packages/dcoscli/marathon/main.py", line 276, in _add
    client.get_app(app_id)
  File "/home/cody/tmp/dcos/lib/python3.5/site-packages/dcos/marathon.py", line 198, in get_app
    return response.json()['app']
KeyError: 'app'
➜  tmp  dcos marathon group add marathon.json
Group '/' already exists
➜  tmp  dcos marathon group add marathon.json
Error: Bean is not valid
```

What finally worked:
```
➜  curl -X PUT -d @marathon.json http://52.36.4.161/marathon/v2/groups
{"version":"2016-02-10T22:51:45.789Z","deploymentId":"057491e6-cf9d-4550-b076-23a068179092"}% 
```

Can give you the marathon.json I'm using offline.

**Comment by tamarrow** [comment]
@jsancio this is because marathon supports `POST` and `PUT` for certain endpoints, and we always use `POST`

**Comment by cmaloney** [comment]
https://github.com/pierlo-upitup/marathon-groups-sanitizer could be a good reference for what is needed to do this.

**Comment by jsancio** [comment]
I think we should implement this in Marathon. I think Marathon should define this operation that give you a JSON object that is rePOSTable or rePUTable back to marathon for both groups and applications.

cc @aquamatthias
