### ISSUE TITLE
CLI exception when installing package with '--options' arg

### ISSUE THREAD

**Issue by nickbp** [mesosphere/dcos-cli#499]
nick@augustao:~/vm-install/code/dcos-tests$ cat ./tmp123.json
{"kafka": {"plan-strategy": "INSTALL", "framework-name": "kafkatest", "pv": false, "broker-count": 2, "placement-strategy": "NODE"}}

nick@augustao:~/vm-install/code/dcos-tests$ dcos --log-level=INFO package install --yes kafka  --options=./tmp123.json
2016-02-24 18:04:24,790 /home/nick/vm-install/code/dcos-cli/dcos/http.py:_request:69 - Sending HTTP ['get'] to ['http://pool-f8e9-elasticl-bqriur1p1av3-1095924404.us-west-2.elb.amazonaws.com/capabilities']: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1'}
2016-02-24 18:04:24,792 /home/nick/vm-install/code/dcos-cli/cli/env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:207 - Starting new HTTP connection (1): pool-f8e9-elasticl-bqriur1p1av3-1095924404.us-west-2.elb.amazonaws.com
2016-02-24 18:04:24,862 /home/nick/vm-install/code/dcos-cli/dcos/http.py:_request:91 - Received HTTP response [200]: {'Date': 'Thu, 25 Feb 2016 02:04:24 GMT', 'Content-Length': '48', 'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Connection': 'keep-alive', 'Server': 'openresty/1.7.10.2'}
2016-02-24 18:04:24,862 /home/nick/vm-install/code/dcos-cli/dcos/http.py:_request:69 - Sending HTTP ['post'] to ['http://pool-f8e9-elasticl-bqriur1p1av3-1095924404.us-west-2.elb.amazonaws.com/package/describe']: {'Content-Type': 'application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v1'}
2016-02-24 18:04:24,863 /home/nick/vm-install/code/dcos-cli/cli/env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:207 - Starting new HTTP connection (1): pool-f8e9-elasticl-bqriur1p1av3-1095924404.us-west-2.elb.amazonaws.com
2016-02-24 18:04:24,934 /home/nick/vm-install/code/dcos-cli/dcos/http.py:_request:91 - Received HTTP response [200]: {'Date': 'Thu, 25 Feb 2016 02:04:24 GMT', 'Content-Length': '8929', 'Content-Type': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v1', 'Connection': 'keep-alive', 'Server': 'openresty/1.7.10.2'}
This will install Apache Kafka DCOS Service.
2016-02-24 18:04:24,935 /home/nick/vm-install/code/dcos-cli/dcos/http.py:_request:69 - Sending HTTP ['post'] to ['http://pool-f8e9-elasticl-bqriur1p1av3-1095924404.us-west-2.elb.amazonaws.com/package/render']: {'Content-Type': 'application/vnd.dcos.package.render-request+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.package.render-response+json;charset=utf-8;version=v1'}
2016-02-24 18:04:24,936 /home/nick/vm-install/code/dcos-cli/cli/env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:207 - Starting new HTTP connection (1): pool-f8e9-elasticl-bqriur1p1av3-1095924404.us-west-2.elb.amazonaws.com
2016-02-24 18:04:25,019 /home/nick/vm-install/code/dcos-cli/dcos/http.py:_request:91 - Received HTTP response [400]: {'Date': 'Thu, 25 Feb 2016 02:04:24 GMT', 'Content-Length': '779', 'Content-Type': 'application/vnd.dcos.package.error+json;charset=utf-8;version=v1', 'Connection': 'keep-alive', 'Server': 'openresty/1.7.10.2'}
Traceback (most recent call last):
  File "/home/nick/vm-install/code/dcos-cli/cli/env/bin/dcos-package", line 9, in <module>
    load_entry_point('dcoscli===SNAPSHOT', 'console_scripts', 'dcos-package')()
  File "/home/nick/vm-install/code/dcos-cli/cli/dcoscli/package/main.py", line 25, in main
    return _main()
  File "/home/nick/vm-install/code/dcos-cli/cli/dcoscli/main.py", line 130, in wrapper
    result = func(*args, **kwargs)
  File "/home/nick/vm-install/code/dcos-cli/cli/dcoscli/package/main.py", line 46, in _main
    return cmds.execute(_cmds(), args)
  File "/home/nick/vm-install/code/dcos-cli/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/home/nick/vm-install/code/dcos-cli/cli/dcoscli/package/main.py", line 365, in _install
    options = pkg.options(user_options)
  File "/home/nick/vm-install/code/dcos-cli/dcos/cosmospackage.py", line 399, in options
    self.marathon_json(user_options)
  File "/home/nick/vm-install/code/dcos-cli/dcos/cosmospackage.py", line 381, in marathon_json
    response = Cosmos(self._cosmos_url).cosmos_post("render", params)
  File "/home/nick/vm-install/code/dcos-cli/dcos/cosmospackage.py", line 224, in check_for_cosmos_error
    error_msg = _format_error_message(response.json())
  File "/home/nick/vm-install/code/dcos-cli/dcos/cosmospackage.py", line 508, in _format_error_message
    error_message = _format_json_schema_mismatch_message(error)
  File "/home/nick/vm-install/code/dcos-cli/dcos/cosmospackage.py", line 529, in _format_json_schema_mismatch_message
    expected = "Expected: {}\n".format(",".join(err.get("expected")))
TypeError: can only join an iterable

**Comment by nickbp** [comment]
Threw a log.error() into the code at cosmospackage.py:508, here's the content of the 'error' param:

2016-02-24 18:07:29,215 /home/nick/vm-install/code/dcos-cli/dcos/cosmospackage.py:_format_error_message:500 - {u'data': {u'errors': [{u'ignored': [u'desription'], u'domain': u'syntax', u'schema': {u'loadingURI': u'#', u'pointer': u'/properties/kafka/properties/ld-library-path'}, u'message': u'the following keywords are unknown and will be ignored: [desription]', u'level': u'warning'}, {u'ignored': [u'desription'], u'domain': u'syntax', u'schema': {u'loadingURI': u'#', u'pointer': u'/properties/kafka/properties/ld-library-path'}, u'message': u'the following keywords are unknown and will be ignored: [desription]', u'level': u'warning'}, {u'ignored': [u'desription'], u'domain': u'syntax', u'schema': {u'loadingURI': u'#', u'pointer': u'/properties/kafka/properties/ld-library-path'}, u'message': u'the following keywords are unknown and will be ignored: [desription]', u'level': u'warning'}]}, u'message': u'Options JSON failed validation', u'type': u'JsonSchemaMismatch'}

**Comment by nickbp** [comment]
Not clear where 'desription' is coming from.

**Comment by nickbp** [comment]
Here's one for installing chronos, same exception from dcos-cli:

{u'data': {u'errors': [{u'ignored': [u'integer'], u'domain': u'syntax', u'schema': {u'loadingURI': u'#', u'pointer': u'/properties/chronos/properties/leader-max-idle-time'}, u'message': u'the following keywords are unknown and will be ignored: [integer]', u'level': u'warning'}, {u'ignored': [u'integer'], u'domain': u'syntax', u'schema': {u'loadingURI': u'#', u'pointer': u'/properties/chronos/properties/leader-max-idle-time'}, u'message': u'the following keywords are unknown and will be ignored: [integer]', u'level': u'warning'}]}, u'message': u'Options JSON failed validation', u'type': u'JsonSchemaMismatch'}

**Comment by tamarrow** [comment]
fixed.
